# Generated by Django 4.0.6 on 2022-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmedicine',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
