# Generated by Django 4.1 on 2022-08-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_addmedicine_expiry_addmedicine_menu_addmedicine_mrp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddMedicine',
        ),
    ]
