# Generated by Django 4.1 on 2022-08-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_addmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('menu', models.DateField()),
                ('expiry', models.DateField()),
                ('rate', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
