# Generated by Django 4.1 on 2022-08-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_addmedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmedicine',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='addmedicine',
            name='menu',
        ),
    ]
