# Generated by Django 4.1 on 2022-08-07 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_addmedicine_expiry_remove_addmedicine_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmedicine',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 7, 8, 29, 20, 823296, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
