# Generated by Django 4.1 on 2022-08-07 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_addmedicine_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmedicine',
            old_name='date',
            new_name='expiry_date',
        ),
        migrations.AddField(
            model_name='addmedicine',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 8, 7, 8, 38, 21, 78024, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
