# Generated by Django 4.1 on 2022-08-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_date_addmedicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmedicine',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
